### ISSUE TITLE
Reference Genome & Index for 'mm38_long_polya'

### ISSUE THREAD

**Issue by zakieh-tayyebi** [dpeerlab/seqc#14]
Hi!
I was wondering if the files in 'seqc-public/genomes' are available for public. I can list the files in, for example, 's3://seqc-public/genomes/mm38_long_polya/', but I can not 'aws s3 sync' them.
I only need to know what genome reference and what annotations were used for the 'mm38_long_polya' index, so I don't actually need to download the files.
Thank you!

**Comment by hisplan** [comment]
Hi,

Sorry for the late response. That was built before my time, so I'm not 100% sure, but based on the `genomeParameters.txt` file which was generated by STAR, I guess it's GRCm38 / Ensembl 87.

```
### STAR   --runMode genomeGenerate   --runThreadN 20   --genomeDir m38_long_polya   --genomeFastaFiles Mus_musculus.GRCm38.dna.primary_assembly.fa      --sjdbGTFfile Mus_musculus.GRCm38.87.long_polya.gtf   --sjdbOverhang 100
versionGenome	20201
genomeFastaFiles	Mus_musculus.GRCm38.dna.primary_assembly.fa
genomeSAindexNbases	14
genomeChrBinNbits	18
genomeSAsparseD	1
sjdbOverhang	100
sjdbFileChrStartEnd	-
sjdbGTFfile	Mus_musculus.GRCm38.87.long_polya.gtf
sjdbGTFchrPrefix	-
sjdbGTFfeatureExon	exon
sjdbGTFtagExonParentTranscript	transcript_id
sjdbGTFtagExonParentGene	gene_id
sjdbInsertSave	Basic
```

Closing this. Please feel free to reopen if you still have issues.

Thanks.
