### ISSUE TITLE
Error- botocore.exceptions.NoRegionError: You must specify a region.

### ISSUE THREAD

**Issue by ritututeja** [dpeerlab/seqc#15]
**Describe the bug**
botocore.exceptions.NoRegionError: You must specify a region.

**To Reproduce**
1. Dockerized seqc for integrating as an app in CyVerse Discovery Environment. 
2. docker run --rm reetututeja/seqc:0.21 SEQC index -h
3. Also tried with the sample dataset- docker run --rm reetututeja/seqc:0.21 SEQC index --organism homo_sapiens   --ensemble-release 93   --valid-biotypes protein_coding lincRNA antisense IG_V_gene IG_D_gene IG_J_gene IG_C_gene TR_V_gene TR_D_gene TR_J_gene TR_C_gene   --read-length 101   --folder index   --local

**Expected behavior**
I am trying seqc with the sample dataset provided on this github repo

**Screenshots**
<img width="1133" alt="Screen Shot 2021-06-01 at 4 12 12 PM" src="https://user-images.githubusercontent.com/2131557/120401141-28f6be00-c2f4-11eb-9028-83607ed1754e.png">

**Assay**
- 10x v2/v3, Drop-seq, In-drop, ...

**Runtime Environment**
 - SEQC Version [e.g. v0.2.2]
 - HPC/AWS/GCP/Desktop

**Additional context**

**Comment by hisplan** [comment]
Hi,

Sorry for the late reply. You can find the pre-built dockerized SEQC here:
https://github.com/dpeerlab/seqc-docker

About the error you mentioned:
Even though SEQC can run locally using the `--local` parameter, SEQC was actually designed to run on AWS, thus you see that error message `NoRegionError: You must specify a region` even though you're trying to run it locally. The trick is that you can just set any AWS region of your choice to ignore that message. For example:

```
export AWS_DEFAULT_REGION=us-east-1
```

For Docker, you can do something like this:

```
docker run -it --rm -e AWS_DEFAULT_REGION=us-east-1 hisplan/seqc:0.2.7
```

I hope that helps. Closing this. Feel free to reopen if you still have issues.

Thanks!
