### ISSUE TITLE
Error when using SEQC run

### ISSUE THREAD

**Issue by fitzgeraldZoeky** [dpeerlab/seqc#3]
Hi, 

I've emailed Jaeyoung for help and been told to create an issue here. 

I got error when using SEQC to process drop-seq dataset. Here are my input and error messages. I hope you can help me with it. Thanks !

**input:**

 SEQC run --local \

-o seqcrun_ \

-g ./mm10/0.5m_2.fq.gz \

-b ./mm10/0.5m_1.fq.gz \

-i index \

drop_seq

**error:**

findfont: Font family ['Raleway'] not found. Falling bau Sans.

findfont: Font family ['Lato'] not found. Falling back ans.

SEQC: 2019-09-15 17:07:17: mutt was not found on this memail will not be sent to the user upon termination of

SEQC: 2019-09-15 17:07:17: Estimated min_poly_t=0

SEQC: 2019-09-15 17:08:26: instance  termination requescessful, this is the final log entry.

Traceback (most recent call last):

  File "/usr/local/lib/python3.6/site-packages/seqc-0.2egg/seqc/core/run.py", line 300, in run

    error_rate = platform.apply_barcode_correction(ra, e_files)

  File "/usr/local/lib/python3.6/site-packages/seqc-0.2egg/seqc/platforms.py", line 597, in apply_barcode_corr

    barcode_correction.drop_seq(ra)

  File "/usr/local/lib/python3.6/site-packages/seqc-0.2egg/seqc/barcode_correction.py", line 202, in drop_seq

    rmt_length = DNA3Bit.seq_len( ra.data['rmt'][idx[0]

**IndexError: index 0 is out of bounds for axis 0 with size 0**

**Comment by hisplan** [comment]
Hi,

Did you build the STAR index? Just curious what `-i index` is pointing to. Could you attach the `seqc_log.txt` file to this ticket? Also, it would be helpful if you could send me the first 100 reads of both R1/R2 FASTQ files.

**Comment by fitzgeraldZoeky** [comment]
Hi,

The "index" file is built by STAR.

The input of STAR, log file and FASTQ files are as follow. Thank you !

input:
STAR --runThreadN 20 --runMode genomeGenerate --genomeDir STAR_index/ --genomeFastaFiles mm10.fa --sjdbGTFfile mm10.gtf --sjdbOverhang 59

I changed file name("STAR_index/" to "index") after finishing because it seemed to have double '/'.

FASTQ file:
1:
![image](https://user-images.githubusercontent.com/45311117/65098131-89977780-d9f9-11e9-9a93-af852c5e4c12.png)

2:
![image](https://user-images.githubusercontent.com/45311117/65098240-97e59380-d9f9-11e9-9111-e8a1835fda8b.png)

files:
[0.5m_2.txt](https://github.com/dpeerlab/seqc/files/3624019/0.5m_2.txt)
[0.5m_1.txt](https://github.com/dpeerlab/seqc/files/3624020/0.5m_1.txt)
[seqc_log.txt](https://github.com/dpeerlab/seqc/files/3624021/seqc_log.txt)

**Comment by hisplan** [comment]
So, it looks like the exception was thrown when SEQC was trying to correct cell barcodes.

The correction algorithm runs for only those reads that meet certain criteria - e.g. reads must be aligned to transcriptome (more specifically exonic region). 

I suspect that for whatever reasons, none of the reads satisfied the criteria. What FASTA/GTF did you use to build the STAR index? Do you have the URLs where I can download the files and take a look?

**Comment by fitzgeraldZoeky** [comment]
Here it is:
ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE63nnn/GSE63472/suppl/GSE63472_mm10_reference_metadata.tar.gz

Thanks !

**Comment by hisplan** [comment]
I took a look at the GTF file that you used. SEQC first searches for the records with the feature field (column 3) set to `transcript`, and then `exon`. Basically, your GTF does not have any `transcript` records, which is the reason your run failed.

I'm not sure if you must use this particular GTF, but we know for sure that GTF from Ensembl works.

**Comment by fitzgeraldZoeky** [comment]
Thanks for your patiance, Your guidance really helps me.

Thank you and your team very much !!
