### ISSUE TITLE
Failed to install SeqC

### ISSUE THREAD

**Issue by pgdurand** [dpeerlab/seqc#9]
**Describe the problem**

I have to install SeqC on a big cluster infrastructure (>400 computing nodes) and I must use Conda to isolate softwares we install.

Considering SeqC, I did this using Anaconda 4.7.2 :

First, prepare a conda env for your software:

```
conda create -p /path/to/conda-env/seqc-0.2.5
conda activate /path/to/conda-env/seqc-0.2.5
```

Then, following the SeqC README.md:

```
conda install python   #(I got Python 3.8)
pip install Cython #(ok)
pip install numpy  #(ok)
pip install bhtsne  #(ok)
conda install -c anaconda hdf5 #(ok)
conda install -c bioconda samtools #(ok)
conda install -c bioconda star #(ok)
cd /path/to/conda-env/seqc-0.2.5
mkdir git-repo ; cd git-repo
git clone https://github.com/dpeerlab/seqc.git #(ok)
cd seqc
python setup.py install
```

This last command failed as follows:

```
Installed /appli/conda-env/bioinfo/seqc-0.2.5/lib/python3.8/site-packages/seqc-0.2.5-py3.8.egg
Processing dependencies for seqc==0.2.5
Searching for magic@ https://github.com/dpeerlab/magic/archive/v0.1.1.tar.gz
Reading https://pypi.org/simple/magic/
No local packages or working download links found for magic@ https://github.com/dpeerlab/magic/archive/v0.1.1.tar.gz
error: Could not find suitable distribution for Requirement.parse('magic@ https://github.com/dpeerlab/magic/archive/v0.1.1.tar.gz')
```

**Runtime Environment**
 - SEQC Version [e.g. v0.2.5]
 - Anaconda 4.7.2
 - Suse Linux

**Comment by jsimonas** [comment]
Installation of [magic](https://github.com/dpeerlab/magic) beforehand should solve the problem.

**Comment by hisplan** [comment]
Are you still having this issue? If so, can you try this instead of `python setup.py install`?
```
cd seqc
pip install .
```

**Comment by pgdurand** [comment]
Hi,

installation seems ok using "pip install .", thanks. 

Now, how can I run a test of your software on my cluster ? (Given I'm not familiar at all with your tool)

Of note: using "SEQC -h" raises an exception (botocore.exceptions.NoRegionError: You must specify a region) instead of providing command-line help.

Patrick

**Comment by hisplan** [comment]
SEQC was originally built to run on AWS, so you need a small workaround to get it working in non-AWS environments.

Try this:

```
export AWS_DEFAULT_REGION=us-east-1
SEQC -h
```

**Comment by Xiang-Leo** [comment]
Hello, after installing SEQC, there is another question. When I wanted to test this software, I ran `SEQC start` and it came out this result:

> (scRNA) lixiang@cj-7920:/data/lixiang/Breast_cancer/1st_try/SRR7191961$ SEQC start
Traceback (most recent call last):
  File "/home/lixiang/anaconda3/envs/scRNA/bin/SEQC", line 7, in <module>
    main(sys.argv[1:])
  File "/home/lixiang/anaconda3/envs/scRNA/lib/python3.8/site-packages/seqc/core/main.py", line 77, in main
    func(arguments)
  File "/home/lixiang/anaconda3/envs/scRNA/lib/python3.8/site-packages/seqc/core/start.py", line 9, in start
    raise ValueError("-k/--rsa-key does not point to a valid file object. ")
ValueError: -k/--rsa-key does not point to a valid file object.


How can I solve this problem?

**Comment by hisplan** [comment]
Are you trying to run SEQC on Amazon Web Services? If so, `-k` is where you supply your EC2 key pair. `SEQC start` will just launch an EC2 instance, but won't do anything further. If you want to process a scRNA-seq data, use the `SEQC run` command.

**Comment by hisplan** [comment]
We're closing this. Please reopen if you still have an issue. Thanks.
